# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a8a9c189eb3b8172c47f6d966406ee4be39357582bb7c3b6d61f86d2ada9f6b7b34b57f3fa1577bf4b7fef84b771aa87e79490f0f4c7c1f33481b3fb197988e

test:
  secret_key_base: 3f02c2059126062f9c0bfd92173caf842ef4f18b41ea0a3ce0d731ea80a7570d01a90b2ef090b0c889480c46437dc61a17d74e66ffcba9d8a3a2af41b6d597b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
